### ISSUE TITLE
Incompatible Excel theme

### ISSUE THREAD

**Issue by dan-fahey** [nacnudus/tidyxl#32]
Weird little Excel file linked below which will crash the rsession when attempting to open with `xlsx_cells`. I have removed all the original sheets, but this file still causes the crash, so the xlsx file can be used a minimal example.
[minimal.xlsx](https://github.com/nacnudus/tidyxl/files/2027096/minimal.xlsx)
![image](https://user-images.githubusercontent.com/7294692/40369101-2b745304-5dd5-11e8-9b8f-f3b54b41e668.png)

Tested on both Windows and Linux. Was able to get a backtrace of rsession using GDB on Linux:
```
#0  0x00007fe0ee8c7e5e in xlsxstyles::cacheThemeRgb (this=this@entry=0x7ffda6d241e8, path="/home/dan/data-lab/servest-meths/data/test_measures/minimal.xlsx") at xlsxstyles.cpp:93
#1  0x00007fe0ee8c85aa in xlsxstyles::xlsxstyles (this=0x7ffda6d241e8, path="/home/dan/data-lab/servest-meths/data/test_measures/minimal.xlsx") at xlsxstyles.cpp:30
#2  0x00007fe0ee8acf62 in xlsxbook::xlsxbook (this=0x7ffda6d24180, path=..., sheet_paths=..., sheet_names=..., comments_paths=...) at xlsxbook.cpp:32
#3  0x00007fe0ee897e2e in xlsx_cells_ (path="/home/dan/data-lab/servest-meths/data/test_measures/minimal.xlsx", sheet_paths=..., sheet_names=..., comments_paths=...) at tidyxl.cpp:26
#4  0x00007fe0ee88341c in _tidyxl_xlsx_cells_ (pathSEXP=<optimised out>, sheet_pathsSEXP=<optimised out>, sheet_namesSEXP=<optimised out>, comments_pathsSEXP=<optimised out>) at RcppExports.cpp:18
#5  0x00007fe11132cc9c in ?? () from /usr/lib/R/lib/libR.so
#6  0x00007fe11136a20d in Rf_eval () from /usr/lib/R/lib/libR.so
#7  0x00007fe11136ccae in ?? () from /usr/lib/R/lib/libR.so
#8  0x00007fe111369fec in Rf_eval () from /usr/lib/R/lib/libR.so
#9  0x00007fe11136c00f in ?? () from /usr/lib/R/lib/libR.so
#10 0x00007fe111369db6 in Rf_eval () from /usr/lib/R/lib/libR.so
#11 0x00007fe11136ccae in ?? () from /usr/lib/R/lib/libR.so
#12 0x00007fe111369fec in Rf_eval () from /usr/lib/R/lib/libR.so
#13 0x00007fe11136c00f in ?? () from /usr/lib/R/lib/libR.so
#14 0x00007fe111369db6 in Rf_eval () from /usr/lib/R/lib/libR.so
#15 0x00007fe111393632 in Rf_ReplIteration () from /usr/lib/R/lib/libR.so
#16 0x00007fe111393a31 in ?? () from /usr/lib/R/lib/libR.so
#17 0x00007fe111393ae8 in run_Rmainloop () from /usr/lib/R/lib/libR.so
#18 0x0000000000e4206f in rstudio::r::session::runEmbeddedR(rstudio::core::FilePath const&, rstudio::core::FilePath const&, bool, bool, SA_TYPE, rstudio::r::session::Callbacks const&, rstudio::r::session::InternalCallbacks*) ()
#19 0x0000000000e2061f in rstudio::r::session::run(rstudio::r::session::ROptions const&, rstudio::r::session::RCallbacks const&) ()
#20 0x0000000000718d53 in main ()
```

Line #0 gave me a clue that it had something to do with the theme1.xml inside the workbook, so I deleted it and repaired with Excel, which stops the crash. So it seems there's some issue with the RapidXML library and the theme settings in this weird Excel file.

**Comment by dan-fahey** [comment]
Excel 2016 64-bit
